version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: crimson-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aaaa2828
      MYSQL_DATABASE: CrimsonConnect
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app1234
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: danbik77/crimson-backend:1.0
    container_name: crimson-backend
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/CrimsonConnect?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: appuser
      SPRING_DATASOURCE_PASSWORD: app1234
      APP_FRONTEND_URL: http://localhost:3000
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    image: danbik77/crimson-frontend:1.0
    container_name: crimson-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql-data:
