spring.application.name=CrimsonConnect

# MySQL datasource configuration
spring.datasource.url=jdbc:mysql://localhost:3306/CrimsonConnect?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=aaaa2828
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis configuration
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.wsu.crimsonconnect.domain

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=crimsonconnect2025@gmail.com
spring.mail.password=cwww ilbw bqga qprl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Application configuration
app.base-url=http://localhost:8080
app.frontend-url=http://localhost:3000

# Logging configuration
logging.level.com.wsu.crimsonconnect.mapper=INFO
logging.level.org.mybatis=INFO

# JWT
app.jwt.secret=MySuperSecretKeyForJwtToken1234567890
app.jwt.expiration=86400000

server.port=${PORT:8080}
